### ISSUE TITLE
action_base.h(39) : error c2248 : cannot access private ACE_Method_Request::ACE_Method_Request 

### ISSUE THREAD

**Issue by jhenchen** [DOCGroup/DAnCE#92]
### Version
1.3.8
### Host machine and operating system
windows 7 64
### Compiler name and version (including patch level)
Visual Studio 14 2015
### The $ACE_ROOT/ace/config.h file
config-win32.h
### The $ACE_ROOT/include/makeinclude/platform_macros.GNU file
there isn't used.
### Contents of $ACE_ROOT/bin/MakeProjectCreator/config/default.features
there isn't used.
### AREA/CLASS/EXAMPLE AFFECTED:
DAnCE_Deployment_Scheduler
DAnCE_NodeApplication
DAnCE_SHS_CORBA_Transport
...
### The problem effects:

Does it affect compilation, linking, or execution. Please indicate whether ACE/TAO, your application, or both are affected.

### Synopsis

Brief description of the problem

### Description
action_base.h(39) : error c2248 : cannot access private ACE_Method_Request::ACE_Method_Request .
LINK :fatal error LNK1104: cann't open file : "DAnCE_Deployment_Schedulerd.lib"

**Comment by jwillemsen** [comment]
This version is ancient, it could be that Visual Studio 2015 didn't work at that point. Maybe you can try the latest DAnCE version, be aware that it isn't actively maintained on Windows due to lack of sponsoring

**Comment by jwillemsen** [comment]
You mean DAnCE 1.3.8, which ACE/TAO version did you use? That should be the latest ACE 6.5.5, TAO 2.5.5 release. On azure we do compile with Visual Studio 2015 so not sure why you get that error.

**Comment by jhenchen** [comment]
yes, DAnCE is 1.3.8, and ACE 6.5.5,TAO 2.5.5. ACE and TAO were  built successfullly , DAnCE was failed.

**Comment by jwillemsen** [comment]
See https://github.com/DOCGroup/DAnCE/blob/master/azure-pipelines.yml for how we compile DAnCE on azure with Visual Studio 2015. Without xerces DAnCE doesn't really work, can you try the steps as in https://github.com/DOCGroup/DAnCE/blob/master/azure-pipelines.yml. If that doesn't work, please add the exact steps you use to generate the Visual Studio solutions

**Comment by jwillemsen** [comment]
Have you installed all Visual Studio 2015 updates?

**Comment by jhenchen** [comment]
I'm not sure. I will check that.

**Comment by jhenchen** [comment]
It is indeed a problem with vs2015 updates.

**Comment by jhenchen** [comment]
After installing all the updates, all the projects were compiled successfully.

**Comment by jwillemsen** [comment]
Thanks for checking the vs2015 updates, closing.
